language: node_js
node_js:
- 7
addons:
  sauce_connect: true
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run sauce
env:
  global:
  - secure: hpTD5ley0zz1EGguG6Dq6KfHE+zVA0R+4tD9mDutf1uTuhTqVMYGOgso1ZSuayUXgETW7Gf4ij5So0olPWXGmfbwZRpFm9OSC5MEvZimBnHZuu+IsEnUlOTI+ynaINv9E9wAk5y7vNRqM+G6lfBKL8qh2AuGGxA9bSxJ1ePNX6RkPkPGBSeMhRaVByHDqG4Hsdiljwkr7SbxxX2XLvy051z71kn5hpREpXg/pf5Wo4iPC6NW9hvSRZnRMqsJfDrm9H2zekKwBLqv7KFMuaGw7QCEbeVuu5WbGIzK5Rsb3BJcJP8njmtb5XXmMaaKI901G/EmzPGvKa9I8OC2MX0P1lIccd4osCY49A0OOPn7U3E/QcR5mf4ztAv1gNKZykce6KCRDmqqX5OkijU0PYIbUYqqftnBeG9ih3NZBwpCHwzpoMoNn51TFK/6CLFkwjx20wWdboXprBNei0S6OHtqCPwMbkWqQdf4iFZY+JTkifT0LhW8nGWNx4OvKd83MZ38MBKI/bsN+7QgACybpwFSoRsOddPvvo/RPlXCeW7Rgk7nICtEbZrkQpt7s6UV66C4PgJnPRa/Zl4nGRddOzLo39IRYq4zWlfasId00Jmc02MNULubYsjEpeylSw30Gn97ViM/elwmyOGqm+Ee1D+YwLxLKogtJITFGMM/IsS70h8=
  - secure: HAEem+PscWC4L2uRqU6cweK09WxJQK4hdJSMc+fFIzJ3jBQ5A4CaI+SV7WJvOwViU6BUrWqISww1LCeHWYpNgu2EF5rnNM6j3pDY34qqUlRD6kumypL8FZ6x/gqbmuCSvu5qqycZIjVG3o8qjmmBjzxTTm/ZYxrLmyq1fJIc198N6uXYWlkD6I7Ec/hvFURbgnL5XMqbIZ7cFWJzceWokh4W3beGdSQjrCA1VV3zPY3MnExZmynQ2y7LscKGdL/vfyJN4zFz5XbZE/bAuH62DhRUtc6FpNTCsb5LEdbv9UXjfCKn4donv3Yg4MpVNqEGWgaoobO5BoEBxLmptiAWhzXT9yIsQoXkMj/ir98jE5d3ISVjs9ZlLzRo6R7oMxE5j5acmesHoFVc2yYCx5HPQOGS0O9G3rjnRWe49Jh+enSfJc3+6Tz8lLfgEKPQl3I95ZjPhvtzYJq524cb7wSIyqYzfHUDUS7nHAAv5op00qd0FwRJfhkkhlf1CD7b1tC9fZLnT/YnLTurJaZWikz3v1mD9CQwNfHHZcDigRN1Ajze/iCfN8ZLHSmY0gJjWu7MpKSYlcFagolnZN90rwhg9NSvfSNxUOK+wjyGllKp91Lo3pKZZHjkNmoSbmJ1YDgWPPYi+aVFjomtw+4T17U/asn+CDw6Z0e1mhbu67QlALw=
